import { defineTheme } from './base.js'

export const russianTheme = defineTheme({
  id: 'russian',
  name: 'Rusça',
  sourceLanguageCode: 'ru',
  era: 'Soğuk Savaş / KGB Arşivi',
  fontHeading: '"Oswald", "Courier New", sans-serif',
  fontBody: '"Roboto Condensed", "Courier New", sans-serif',
  colors: {
    background: '#150808',
    surface: '#221010',
    surfaceStrong: '#0d0303',
    primary: '#b30000',
    accent: '#ffcc00',
    text: '#f3e6c8',
    textMuted: '#b8967a',
    border: '#4a2020',
    danger: '#ff4d4d',
    success: '#3dff3d',
  },
  audio: {
    radioTrack: 'src/assets/audio/russian/track1.mp3',
    stampSound: 'src/assets/audio/russian/stamp.mp3',
    correctSound: 'src/assets/audio/russian/correct.mp3',
    incorrectSound: 'src/assets/audio/russian/incorrect.mp3',
  },
  effects: {
    paperTexture: true,
    vignette: true,
    scanlines: true,
    flickerOnError: false,
    stampOnAdd: true,
  },
  rankNames: [
    'Köylü',
    'Yoldaş',
    'Gözlemci',
    'Şifreci',
    'Saha Ajanı',
    'Kıdemli Ajan',
    'Yüzbaşı',
    'Binbaşı',
    'Albay',
    'Genel Sekreter',
  ],
})
